name: "Bug report"
description: "Report a TSera CLI bug with reproducible steps"
title: "[bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        **Goal:** make it reproducible quickly. Please include exact commands + logs.
        ⚠️ Do not paste secrets (tokens, API keys, .env values).

  - type: input
    id: tsera_version
    attributes:
      label: "TSera version"
      description: "Output of `tsera --version`"
      placeholder: "e.g. 0.1.0"
    validations:
      required: true

  - type: input
    id: deno_version
    attributes:
      label: "Deno version"
      description: "Output of `deno --version`"
      placeholder: "e.g. 2.1.x"
    validations:
      required: true

  - type: dropdown
    id: install_method
    attributes:
      label: "Installation method"
      options:
        - "JSR (deno install jsr:...)"
        - "Compiled binary (dist)"
        - "From source (git clone)"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "OS"
      options:
        - "Linux"
        - "macOS"
        - "Windows"
    validations:
      required: true

  - type: input
    id: shell
    attributes:
      label: "Shell"
      description: "bash / zsh / fish / pwsh / cmd…"
      placeholder: "e.g. zsh"
    validations:
      required: true

  - type: dropdown
    id: command_area
    attributes:
      label: "Which TSera command is involved?"
      options:
        - "init"
        - "dev"
        - "doctor"
        - "deploy"
        - "update"
        - "export-env"
        - "other / not sure"
    validations:
      required: true

  - type: dropdown
    id: bug_type
    attributes:
      label: "Bug type"
      description: "Helps us route the issue correctly."
      options:
        - "CLI runtime (command fails / crashes / wrong behavior)"
        - "Generated project (scaffold output is broken)"
        - "Both / not sure"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "Exact, minimal steps to reproduce the issue."
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true

  - type: textarea
    id: commands
    attributes:
      label: "Command(s) executed"
      description: "Copy/paste the exact commands you ran."
      render: bash
      placeholder: |
        tsera init my-app
        cd my-app
        tsera dev
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      placeholder: "What you expected to happen."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      placeholder: "What happened instead."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs / output"
      description: |
        Paste the relevant terminal output.
        If available, re-run with `--json` and paste the NDJSON excerpt.
        ⚠️ Remove secrets.
      render: text
      placeholder: |
        (paste logs here)
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
      label: "Reproducibility"
      options:
        - "Always"
        - "Sometimes"
        - "Rarely"
        - "Unable to reproduce"
    validations:
      required: true

  - type: textarea
    id: project_context
    attributes:
      label: "Project context (optional)"
      description: "Helps us reproduce faster."
      placeholder: |
        - New project generated by TSera: yes/no
        - Existing repo / monorepo: yes/no
        - Relevant files: deno.jsonc, import_map, .tsera/* (redact secrets)
        - Anything special (CI, env vars, database, etc.)
    validations:
      required: false

  - type: input
    id: generated_template
    attributes:
      label: "Generated template / target"
      description: "Which template/stack did you generate (if applicable)?"
      placeholder: "e.g. ts-era default / lume / hono / drizzle / ..."
    validations:
      required: false

  - type: textarea
    id: generated_issue
    attributes:
      label: "Generated project issue (if applicable)"
      description: |
        If the CLI succeeded but the generated project is broken, provide:
        - what is broken (imports, build, runtime, links)
        - the exact command to reproduce inside the generated project
      render: bash
      placeholder: |
        cd <generated-project>
        deno task dev
        deno task test
        # or the command that fails
    validations:
      required: false

  - type: dropdown
    id: fresh_project
    attributes:
      label: "Is this a fresh TSera-generated project?"
      options:
        - "Yes (just generated, no manual edits)"
        - "No (I modified files after generation)"
        - "Not applicable"
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I searched existing issues and discussions"
          required: true
        - label: "I removed secrets from logs"
          required: true
