name: "Feature request"
description: "Propose a TSera feature (CLI, generators, core engine, docs)"
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Use this to propose a feature for TSera.
        **Be concrete.** Prefer small, composable changes over big rewrites.

  - type: dropdown
    id: area
    attributes:
      label: "Area"
      description: "Where should this feature live?"
      options:
        - "CLI (commands, UX, flags, outputs)"
        - "Core engine (domain definition → generated artifacts)"
        - "Generators (templates/scaffolding)"
        - "DX / Tooling (dev workflow, CI/CD helpers)"
        - "Docs / Website"
        - "Other / not sure"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem"
      description: "What problem are you trying to solve? What is painful today?"
      placeholder: |
        - Current behavior:
        - Why it’s a problem:
        - Who it impacts:
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "Proposed solution"
      description: "Describe the feature, behavior, and expected outcome."
      placeholder: |
        - What should TSera do?
        - CLI command/flag examples (if relevant)
        - Expected output / generated files (if relevant)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Other ways to solve it (including doing nothing)."
      placeholder: |
        - Alternative A:
        - Alternative B:
        - Why they’re worse:
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: "Scope / artifacts impacted"
      description: "What would change in the TSera unified stack?"
      placeholder: |
        Check what applies:
        - Domain definition / schemas
        - Database (Drizzle)
        - API (Hono)
        - Frontend / pages (Lume/Astro/other)
        - Docs
        - CI/CD
        - Deployment workflows
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance criteria"
      description: "What must be true for this feature to be considered done?"
      placeholder: |
        - [ ] ...
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: "Breaking change?"
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority (your view)"
      options:
        - "Nice to have"
        - "Should have"
        - "Must have"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Additional context / examples"
      description: "Links, screenshots, code snippets, references."
      placeholder: |
        - Similar tools / references:
        - Example project:
        - Anything else:
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I searched existing issues and discussions"
          required: true
        - label: "This request aligns with TSera goals (TypeScript-first, unification, simplicity, automation)"
          required: true
