name: CD GitHub Releases

on:
  workflow_call:
    inputs:
      tag:
        description: "Release tag (e.g., v1.0.0)"
        required: true
        type: string
      release_name:
        description: "Release name"
        required: false
        default: "${{ inputs.tag }}"
        type: string
      body:
        description: "Release notes"
        required: false
        default: ""
        type: string
      draft:
        description: "Create as draft release"
        required: false
        default: "false"
        type: boolean
      prerelease:
        description: "Mark as pre-release"
        required: false
        default: "false"
        type: boolean

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: ${{ inputs.release_name }}
          body: ${{ inputs.body }}
          draft: ${{ inputs.draft == 'true' }}
          prerelease: ${{ inputs.prerelease == 'true' }}
