import { Head } from "@fresh/runtime";

export default function Home() {
  return (
    <>
      <Head>
        <title>TSera • Fresh starter</title>
      </Head>
      <main class="page">
        <header>
          <h1>TSera</h1>
          <p>A minimal Fresh starter connected to the Hono API.</p>
        </header>
        <section>
          <h2>Test the coherence loop</h2>
          <ol>
            <li>
              Start the API: <code>deno task dev</code>
            </li>
            <li>
              Start the frontend: <code>deno run -A web/main.ts</code>
            </li>
            <li>
              Open <code>http://localhost:8000/health</code> and <code>http://localhost:8001</code>
            </li>
          </ol>
          <p>
            Both layers share the types generated by TSera. Edit an entity, rerun
            <code>tsera dev</code>, and watch the artifacts update.
          </p>
        </section>
      </main>
    </>
  );
}
