name: CI - Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      # NOTE: Default backend entrypoint for a TSera-generated project.
      # If your project uses a different entrypoint, adjust this path.
      # Example: app/api/main.ts or a monorepo with multiple apps.
      - name: Cache dependencies
        run: |
          if [ -f "app/back/main.ts" ]; then
            deno cache --lock=deno.lock app/back/main.ts
          else
            echo "⚠️  app/back/main.ts not found, skipping cache step"
          fi

      - name: Export environment variables
        run: |
          # Map branch name to environment
          if [ "${{ github.ref_name }}" = "main" ]; then
            ENV="prod"
          elif [ "${{ github.ref_name }}" = "develop" ]; then
            ENV="staging"
          else
            ENV="dev"
          fi
          deno run -A src/cli/main.ts export-env --env=$ENV --format=github-env --prefix=APP_
        env:
      # Add your secrets here (from GitHub repository settings)
      # DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # API_KEY: ${{ secrets.API_KEY }}

      - name: Build backend
        run: |
          if [ -f "app/back/main.ts" ]; then
            deno compile -A --output ./dist/backend app/back/main.ts
          else
            echo "⚠️  app/back/main.ts not found, skipping build step"
            exit 1
          fi
